FROM us-central1-docker.pkg.dev/hubs-dev-333333/ocho-osai/osai-ubuntu/cuda-pip-torch:ubuntu23.10

RUN apt-get update && apt-get install -y git

RUN useradd -ms /bin/bash john
RUN mkdir -p /etc/sudoers.d
RUN echo "john ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/john
USER john
WORKDIR /home/john/

RUN pip install -Uq jupyterlab ipywidgets
ENV PATH="/home/john/.local/bin:${PATH}"
