---
- name: Setup Server
  hosts: servers
  vars:
    libtinfo5_url: "http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb"
    libtinfo5_deb: "/tmp/libtinfo5_6.4-2_amd64.deb"
  become: yes
  tasks:
    - name: Install nice-to-have packages
      apt:
        name:
          - bat #batcat
          - curl
          - git
          - htop
          - iftop
          - net-tools
          - tree
        state: latest

    # -------------------------- DOCKER -------------------------- #
    - name: Install prerequisites for Docker GPG key
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set correct permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: "a+r"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update Repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Add user to Docker group
      user:
        name: john
        groups: docker
        append: yes
    # -------------------------- END DOCKER -------------------------- #

    # -------------------------- CUDA -------------------------- #

    # NOTE: The latest version of GCC (13.2.0 at the time of this comment) is newer than what CUDA supports.
    # When trying to compile a cuda program with nvcc, it issues this error:
    #
    #     error: #error -- unsupported GNU version! gcc versions later than 12 are not supported!
    #            The nvcc flag '-allow-unsupported-compiler' can be used to override this version check;
    #            however, using an unsupported host compiler may cause compilation failure or incorrect run time execution.
    #            Use at your own risk.
    #
    # Therefore, if we see gcc / cuda errors, we should install an alternative version of gcc.
    # There are many available:
    #
    #     apt-cache search gcc
    #
    # NOTE: The build-essential package also includes other packages.
    #
    # Depends: libc6-dev | libc-dev, gcc (>= 4:12.3), g++ (>= 4:12.3), make, dpkg-dev (>= 1.17.11)
    #
    # I didn't realize I could JUST install gcc. I'm not sure which (if any) of the others are actually necessary.
    - name: Install gcc
      apt:
        name:
          - build-essential
        state: latest

    - name: Install necessary kernel headers
      apt:
        name:
          - linux-headers-6.5.0-10-generic
          - linux-headers-generic
        state: present
        update_cache: yes

    # The CUDA Keyring package includes the key that we have to trust when installing nvidia's cuda packages
    # https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network
    - name: Install CUDA Keyring
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        dest: /tmp/cuda-keyring_1.1-1_all.deb
        force: no

    - name: Install CUDA Keyring Package
      command:
        cmd: dpkg -i /tmp/cuda-keyring_1.1-1_all.deb

    - name: Update Repositories
      apt:
        update_cache: yes

    # libtinfo5 is a cuda dependency that doesn't seem to be available
    # through the standard apt sources (yet) on ubuntu 23.10,
    # so we download whatever version we can find online.
    - name: Download libtinfo5 package
      get_url:
        url: "{{ libtinfo5_url }}"
        dest: "{{ libtinfo5_deb }}"
        force: no

    - name: Install libtinfo5 package
      ansible.builtin.apt:
        deb: "{{ libtinfo5_deb }}"

    - name: Install CUDA dependencies
      apt:
        name:
          - libtinfo5
        state: latest

    # There are alternative meta packages of CUDA available
    # The "cuda" package installs everything, including the proprietary drivers
    # You can switch to the open drivers if you prefer
    # https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#switching-between-driver-module-flavors
    #
    # This is a large download. Ansible was paused here for a long time.
    - name: Install CUDA (Full Package including Driver)
      apt:
        name: cuda
        state: latest

    - name: Add CUDA to PATH for all users
      blockinfile:
        path: /etc/profile.d/cuda.sh
        create: yes
        block: |
          #!/bin/sh
          export PATH=$PATH:/usr/local/cuda/bin

    # -------------------------- END CUDA -------------------------- #

    # -------------------------- NVIDIA-CONTAINER-TOOLKIT -------------------------- #

    - name: Download the NVIDIA repository GPG key if it does not exist
      shell: |
        if [ ! -f /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg ]; then
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        fi
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add the NVIDIA repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/amd64 /" | tee /etc/apt/sources.list.d/nvidia_github_io_libnvidia_container_stable_ubuntu22_04.list
      args:
        creates: /etc/apt/sources.list.d/nvidia_github_io_libnvidia_container_stable_ubuntu22_04.list

    - name: Update Repositories
      apt:
        update_cache: yes

    - name: Install nvidia-container-toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        update_cache: yes
        state: present

    - name: Configure NVIDIA Container Runtime for Docker
      command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    # -------------------------- END NVIDIA-CONTAINER-TOOLKIT -------------------------- #

    # -------------------------- GOOGLE CLOUD CLI -------------------------- #
    - name: Install gcloud cli dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
          - sudo
        state: latest

    - name: Ensure google-cloud-sdk.list exists and contains the required repo line
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/google-cloud-sdk.list
        line: "deb [signed-by=/usr/share/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main"
        create: yes
        state: present

    - name: Download cloud.google.asc if it does not exist
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/cloud.google.asc
        force: no

    - name: Update APT cache and install gcloud CLI
      ansible.builtin.apt:
        update_cache: yes
        name: google-cloud-cli
        state: present

    # -------------------------- END GOOGLE CLOUD CLI -------------------------- #
