---
- name: Setup Server
  hosts: all
  vars:
    libtinfo5_url: "http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb"
    libtinfo5_deb: "/tmp/libtinfo5_6.4-2_amd64.deb"
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install nice-to-have packages
      apt:
        name:
          - bat # batcat
          - curl
          - git
          - htop
          - iftop
          - net-tools
          - tree
        state: latest

    # -------------------------- DOCKER -------------------------- #
    - name: Install prerequisites for Docker GPG key
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes

    - name: Ensure /etc/apt/keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set correct permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: "a+r"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update Repositories
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    # -------------------------- END DOCKER -------------------------- #

    # -------------------------- NVIDIA-CONTAINER-TOOLKIT -------------------------- #

    - name: Download the NVIDIA repository GPG key if it does not exist
      shell: |
        if [ ! -f /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg ]; then
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        fi
      args:
        creates: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg

    - name: Add the NVIDIA repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://nvidia.github.io/libnvidia-container/stable/deb/amd64 /" | tee /etc/apt/sources.list.d/nvidia_github_io_libnvidia_container_stable_ubuntu22_04.list
      args:
        creates: /etc/apt/sources.list.d/nvidia_github_io_libnvidia_container_stable_ubuntu22_04.list

    - name: Update Repositories
      apt:
        update_cache: yes

    - name: Install nvidia-container-toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        update_cache: yes
        state: present

    - name: Configure NVIDIA Container Toolkit for Docker
      command: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes

    # -------------------------- END NVIDIA-CONTAINER-TOOLKIT -------------------------- #

    # -------------------------- GOOGLE CLOUD CLI -------------------------- #
    - name: Install gcloud cli dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
          - sudo
        state: latest

    - name: Ensure google-cloud-sdk.list exists and contains the required repo line
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/google-cloud-sdk.list
        line: "deb [signed-by=/usr/share/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main"
        create: yes
        state: present

    - name: Download cloud.google.asc if it does not exist
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/cloud.google.asc
        force: no

    - name: Update APT cache and install gcloud CLI
      ansible.builtin.apt:
        update_cache: yes
        name: google-cloud-cli
        state: present

    # -------------------------- END GOOGLE CLOUD CLI -------------------------- #

    # -------------------------- NVIDIA DRIVER -------------------------- #
    - name: Get the running kernel version
      command: uname -r
      register: kernel_version

    - name: Install gcc and necessary kernel headers
      apt:
        name:
          - build-essential
          - "linux-headers-{{ kernel_version.stdout }}"
        state: latest
        update_cache: yes

    - name: Add Nvidia driver repository
      apt_repository:
        repo: ppa:graphics-drivers/ppa

    - name: Install Nvidia Driver 545
      apt:
        name: nvidia-driver-545
        state: latest
        update_cache: yes

    - name: Reboot the machine
      reboot:
    # -------------------------- END NVIDIA DRIVER -------------------------- #
